# --------------------------------------------------------------------------
#  CppADCodeGen: C++ Algorithmic Differentiation with Source Code Generation:
#    Copyright (C) 2020 Joao Leal
#
#  CppADCodeGen is distributed under multiple licenses:
#
#   - Eclipse Public License Version 1.0 (EPL1), and
#   - GNU General Public License Version 3 (GPL3).
#
#  EPL1 terms and conditions can be found in the file "epl-v10.txt", while
#  terms and conditions for the GPL3 can be found in the file "gpl3.txt".
# ----------------------------------------------------------------------------
# Author: Joao Leal

language: cpp

addons:
  apt: &common_apt
    sources: &common_sources
      - kubuntu-backports
    packages: &common_packages
      - cmake
      - texlive-extra-utils
      - texlive-fonts-extra
      - texlive-latex-recommended

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          <<: *common_apt
          sources:
            - *common_sources
            - llvm-toolchain-bionic-9
            - ubuntu-toolchain-r-test  # gcc-9
          packages:
            - *common_packages
            - libclang-9-dev
            - llvm-9-dev
            - clang-9
            - gcc-9
            - g++-9
      env:
        - LLVM_VERSION=9
        - OVERRIDE_CC="CC=gcc-9" OVERRIDE_CXX="CXX=g++-9"
    - os: linux
      dist: bionic
      compiler: clang
      addons:
        apt:
          <<: *common_apt
          sources:
            - *common_sources
            - llvm-toolchain-bionic-9
            - ubuntu-toolchain-r-test  # gcc-9
          packages:
            - *common_packages
            - libclang-9-dev
            - llvm-9-dev
            - clang-9
      env:
        - LLVM_VERSION=9
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          <<: *common_apt
          sources:
            - *common_sources
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test  # gcc-9
          packages:
            - *common_packages
            - libclang-3.6-dev
            - llvm-3.6-dev
            - clang-3.6
            - gcc-9
            - g++-9
      env:
        - LLVM_VERSION=3.6
        - OVERRIDE_CC="CC=gcc-9" OVERRIDE_CXX="CXX=g++-9"
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - LLVM_VERSION=3.6
      addons:
        apt:
          <<: *common_apt


# use travis-ci docker based infrastructure
sudo: false

before_install:
  - if [ "$CXX" == "g++" ];     then export CC="$(which gcc-9)"   CXX="$(which g++-9)"; fi
  - if [ "$CXX" == "clang++" ]; then export CC="$(which clang-9)" CXX="$(which clang++-9)"; fi

install:
  - mkdir cppadcg_deps
  - cd cppadcg_deps
  # get CppAD:
  # - git clone https://github.com/coin-or/CppAD.git cppad
  # - cd cppad
  - CPPAD_VERSION_NAME=20200000.3
  - wget https://github.com/coin-or/CppAD/archive/${CPPAD_VERSION_NAME}.tar.gz
  - tar -xzf ${CPPAD_VERSION_NAME}.tar.gz
  - cd CppAD-${CPPAD_VERSION_NAME}
  - mkdir build
  - mkdir install
  - CPPAD_HOME=`pwd`/install/include
  - echo $CPPAD_HOME
  - cd build
  - cmake -Dcppad_prefix:PATH=../install -Dcppad_cxx_flags="-Wall -std=c++11 -Wshadow" ..
  - make install
  - cd ../..
  # get Eigen:
  - wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2
  - tar -jxf 3.3.7.tar.bz2
  - cd eigen-eigen-323c052e1731
  - mkdir -p install_eigen/include/eigen3
  - cp -r Eigen ./install_eigen/include/eigen3/
  - EIGEN_HOME=`pwd`/install_eigen/include/eigen3
  - echo $EIGEN_HOME
  #
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=DEBUG -DGOOGLETEST_GIT=ON -DUSE_VALGRIND=OFF -DENABLE_THREAD_POOL_TESTS=OFF -DLLVM_VERSION=${LLVM_VERSION} -DCPPAD_HOME=$CPPAD_HOME -DEIGEN3_INCLUDE_DIR=$EIGEN_HOME ..
  - cd test
  - make -j2 build_tests
  - CTEST_OUTPUT_ON_FAILURE=TRUE make test
  - cd ..
  - make DESTDIR=cppadcg-install-dir install
  - make DESTDIR=cppadcg-install-dir uninstall
